### ISSUE TITLE
Will you be so kind to add swap tagNames button?

### ISSUE THREAD

**Issue by Vadim-Moshev** [CyberLight/caninclude#1]
Hello. Will you be so kind to add swap tagNames button? I mean the following thing.
Once I pressed this button, the tags names I typed into the text fields swaped.

Lets imagine the following situation. I asked the canIInclude application, 'can I include `<a>` into `<img>` tag?' Later I've realized I've made a mistake, cause I understand `<a>` can't be incuded into `<img>`. There is no such button yet so I have to clear both of these fields and type the names anew. If this buttond existed it would be much easier to rich this purpose.

Thank you in advanced.

**Comment by CyberLight** [comment]
![Demo](https://user-images.githubusercontent.com/2742061/83996442-013d7600-a97e-11ea-9b32-05963ebbbea8.gif)

**Comment by CyberLight** [comment]
@Vadim-Moshev, please check the functionality of your ticket :). I hope I did what you meant. And if all ok, please close this ticket

**Comment by Vadim-Moshev** [comment]
@CyberLight 
Thank you. But this isn't quite what I meant. I meant the button that phisically changes (swaps) values of these text fields. Like this:

before button pressed:
text field 1: `<a>`
text field 2: `<img>`
(Can I include `<a>` into `<img>` ?)

After button pressed:
text field 1: `<img>`
text field 2: `<a>`
(Can I include `<img>` into `<a>` ?)

Now we are about to submit form and find out, if we can include `<img>` to `a`.

**Comment by CyberLight** [comment]
@Vadim-Moshev , thanks for your feedback and a very good formed task! :)

I understand you, the fact is that I do not write client code in JavaScript (at this stage of the application), for this reason, and no way for exchanging values ​​between fields on the client side without writing client JavaScript code.

The values will be changed in the text fields, but only **after the form is submitted to the server** (since there is no client JavaScript). At the same time, the URL in the browser will not change, since this requires an additional redirect with changing the URL data.

**Comment by Vadim-Moshev** [comment]
@CyberLight 
Ok, I've got it. I think it's necessary to find out which files to be edited to add that functionality I was talking about. I have to find free time to do that and send you pull request. How about that?

P. S. I trully understand I can send you PR at anytime without asking permission, but you could reject it. So do you mind if I will try to add that functionality and send you PR, if I find free time?

**Comment by CyberLight** [comment]
@Vadim-Moshev , this is normal if you try to send PR to me :)
But I think that we do not understand each other.
In the current version of the project, to implement the logic on the client side, it is necessary to update all components, since now all components are focused only on server-side rendering using the **htm** module.
If you think that this is a simple task that can be implemented in this ticket, then this is not so. We need new tickets for implementing the client version of each component so that we can write client logic on a Preact

**Comment by Vadim-Moshev** [comment]
@CyberLight 
As far as I understand, there is much work to implement that funcionality, no matter which ticket we are in. So I think that ticket can be clossed. But first... Let me to give you an advice about swap button tabindex. Sorry I didn't create a new ticket. Anyway we are talking about the same functionality you have added within this ticket.

So, let's have a look on the following case. A user typed some tag name in the first input. Then he pressed `tab` key on his keyboard. Then swap button got the focus. I think the user indended to type the second tag name, not swap tha tags names (moreover, the second field can be blank at all). So, how about the followind sequence:
1. user typed the first tag name;
2. user pressed `tab` key;
3. the second textfield got the focus;
4. user is about to type the second tag name?

**Comment by CyberLight** [comment]
@ Vadim-Moshev thanks for the tip!
Do not be afraid to create new tasks with your thoughts :). If the task is not correct or not needed, you can delete it or edit it without any problems. And of course, you can create new tasks and send PR without worrying.

I think that if this ticket can be closed, then I close this ticket and create a new ticket with your suggestions, and we can continue discussing the solution for tabindex in the new problem. Because some things need to be discussed before implementation
