### ISSUE TITLE
So this tool doesn't support svg?

### ISSUE THREAD

**Issue by ZerdoX-x** [CyberLight/caninclude#21]
Can i include `svg` into `svg`?
This request in your tool acts like `any-unknown-tag` into `another-unknown-tag` (page refreshes and nothing happens)
 
This works: https://caninclude.glitch.me/can/include/?child=div&parent=button

This doesn't work:&nbsp;&nbsp;https://caninclude.glitch.me/can/include/?child=svg&parent=button
Behavior same as:&nbsp;https://caninclude.glitch.me/can/include/?child=invalid-tag-name&parent=button

**Comment by CyberLight** [comment]
@ZerdoX-x hi!

I looked at the specification and SVG is not included in the HTML section of the specification elements. For this reason, SVG is not included in the collected data.

I hope I answered correctly the problem described in the ticket. I am open to discussion. Thank you for your interest in the service

Please close the application, if the problem is exhausted

<img width="1339" alt="Screen Shot 2020-12-21 at 10 45 35" src="https://user-images.githubusercontent.com/2742061/102740474-18700e00-437a-11eb-909f-f20c562155c0.png">

**Comment by ZerdoX-x** [comment]
Thank you for such a clear answer!
